### ISSUE TITLE
this why?

### ISSUE THREAD

**Issue by 99anhadi** [secrary/SSMA#51]
![cuplikan layar_2018-02-17_13-01-01](https://user-images.githubusercontent.com/26619526/36338478-b2211258-13e2-11e8-9486-2a717df24576.png)
this why? I've installed it but can not ?

**Comment by pielco11** [comment]
It seams that using `pip3` you are accessing to `python2` packages.
You should get something like this:

![screenshot_6](https://user-images.githubusercontent.com/17363750/36343512-818ef56c-140d-11e8-93ef-062e7d6a06b5.png)

Are you using aliases (which is usual when using customized version of shells, like `oh-my-zsh`)?
Please run `which pip3` and if you see something like this:

![screenshot_5](https://user-images.githubusercontent.com/17363750/36343467-fc3f7d0a-140c-11e8-8b4a-ddf5dd797dc1.png)

I suggest you to edit that specific alias, otherwise we will find another way.
